version: '2'
services:
    colisuivi-app:
        image: colisuivi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://colisuivi-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=colisuivi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    colisuivi-mongodb:
        extends:
            file: mongodb.yml
            service: colisuivi-mongodb
